### ISSUE TITLE
Integrations with vscode google translate

### ISSUE THREAD

**Issue by taba929** [tshino/vscode-kb-macro#104]
Hi,
I'm not sure if this is a bug or wrong configuration but i use vs code 1.67.0 with extension vscode google translate 1.4.13 that let me translate the text i select in any other languages. With kb macro I try to record this sequence:
**f4**, for go to the next in global search,
**right arrow**,
**shift + end**, for select the phrases to translate,
**alt + shift + t**, to translate the selected text with vscode google translate
When I play the macro recorded it copy the same phrases in the previous line. 
Any fix?

**Comment by tshino** [comment]
Thank you for the reporting this issue.
I'll take a look at it.

**Comment by tshino** [comment]
I see.

The shortcut `alt+shift+t' to trigger translation is provided by Vscode Google Translate extension.
To enable the shortcut key to be recorded by Keyboard Macro Beta, you should define the corresponding wrapper for the key, since Keyboard Macro Beta is not aware of any other extensions installed together in the user's vscode.

So, could you try to add the following keybinding to your `keybindings.json` and try recording the same sequence again?
```
    {
        "key": "shift+alt+t",
        "command": "kb-macro.wrap",
        "args": {
            "command": "extension.translateTextPreferred"
        },
        "when": "kb-macro.recording && editorTextFocus"
    }
```
It works for me.
- See [the section in the README](https://github.com/tshino/vscode-kb-macro/blob/main/README.md#how-to-enable-your-favorite-custom-keybindings-to-record) about making such wrappers like above. The explanation is for user's own custom keybinding definition, but it applies also to the other extension's keybindings. I'll fix the explanation later.
- You can get the definition of the keyboard shortcut provided by an extension by searching in the Keyboard Shortcuts screen on your VS Code and select `Copy` on the context menu. (see below)
![image](https://user-images.githubusercontent.com/732920/168096763-e9add8db-758d-4b18-a56d-2a276bb1dfba.png)

**Comment by taba929** [comment]
Thankyou tshino,
then it is my pc problem. I try your solution in my pc, but it doesn't work. The problem is the same nothing change.
If in your pc it works, it' s my pc problem. I will inspect.
Thankyou very much

**Comment by tshino** [comment]
Sorry to hear that it doesn't work. :(
Please feel free to post further comments if anything you found on this issue.
